name: app_4
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
     - assets/logo.png
     - assets/detalhe_cliente.png
     - assets/detalhe_contato.png
     - assets/detalhe_empresa.png     
     - assets/detalhe_servico.png 
     - assets/cliente1.png
     - assets/cliente2.png     

